### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dadair-ca** [Atamai/tactics#1]
Hi @dgobbi , what license are we using on the code? Is it GPL/MIT/etc? Or a custom one? I read the LICENSE file but it didn't say anything about basing it off an existing license.

Just wondering in case we want to include GNU tools for future improvements (say getopts, as an example).

**Comment by dgobbi** [comment]
It's the BSD 3-clause license (http://opensource.org/licenses/BSD-3-Clause).  No GNU stuff, I don't want to switch to copyleft.

**Comment by dadair-ca** [comment]
Sounds good!
